In [2]:
import numpy as np

1. Write a NumPy program to test whether none of the elements of a given array is zero.



In [3]:
numbers = np.array([4,5,6,7])

print("Original array:")

print(numbers)

print("Test if none of the elements of the said array is zero:")

print(np.all(numbers))

numbers = np.array([0, 5,6,7])

print("Original array:")

print(numbers)

print("Test if none of the elements of the said array is zero:")

print(np.all(numbers))

Original array:
[4 5 6 7]
Test if none of the elements of the said array is zero:
True
Original array:
[0 5 6 7]
Test if none of the elements of the said array is zero:
False


2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [5]:
x = np.array([1, 2, 0, 0])

print("Original array:")

print(x)

print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))

x = np.array([0, 0, 0, 0])
print("Original array:")
print(x)

print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))

Original array:
[1 2 0 0]
Test whether any of the elements of a given array is non-zero:
True
Original array:
[0 0 0 0]
Test whether any of the elements of a given array is non-zero:
False


3. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [15]:
b = np.array([1, 0, 5, np.nan, np.inf])
print("Original array :")
print(b)
print(...................)
print("Test a given array element-wise for finiteness :")
print(np.isfinite(b))

Original array :
[ 1.  0.  5. nan inf]
Test a given array element-wise for finiteness :
[ True  True  True False False]


4. Write a NumPy program to test element-wise for positive or negative infinity.
​

In [22]:
z = np.array([1, -5, 1.8, np.nan, np.inf])
print("Original array")
print(z)
print("................")
print("Test element-wise for positive or negative infinity:")
print(np.isinf(z))

Original array
[ 1.  -5.   1.8  nan  inf]
.......
Test element-wise for positive or negative infinity:
[False False False False  True]


5. Write a NumPy program to test element-wise for NaN of a given array.

In [23]:
z = np.array([1, 2, np.nan, np.inf])
print("Original array")
print(z)
print("..............")
print("Test element-wise for NaN:")
print(np.isnan(z))


Original array
[ 1.  2. nan inf]
..............
Test element-wise for NaN:
[False False  True False]


6. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [30]:
z = np.array([1, 1+0j, 4.5, 1+1j, 2, 2j])
print("Original array")
print(z)
print("----------------")
print("Checking for complex number:")
print(np.iscomplex(z))
print("------------------")
print("Checking for real number:")
print(np.isreal(z))
print("-----------------")
print("Checking for scalar type:")
print(np.isscalar(1.1))
print(np.isscalar([1.1]))


Original array
[1. +0.j 1. +0.j 4.5+0.j 1. +1.j 2. +0.j 0. +2.j]
----------------
Checking for complex number:
[False False False  True False  True]
------------------
Checking for real number:
[ True  True  True False  True False]
-----------------
Checking for scalar type:
True
False


7. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [6]:
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))

print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))

print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))

print(np.allclose([1.0, np.nan], [1.0, np.nan]))

print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

False
True
False
False
True


8. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [36]:
x = np.array([7, 5])
y = np.array([4, 5])
print("Original numbers:")
print(x)
print("..........")

print(y)
print("Comparison - greater")
print(np.greater(x, y))
print(".........")

print("Comparison - greater than or equal")
print(np.greater_equal(x, y))

print(".................")
print("Comparison - less")
print(np.less(x, y))

print("..................")
print("Comparison - less than or equal")
print(np.less_equal(x, y))


Original numbers:
[7 5]
..........
[4 5]
Comparison - greater
[ True False]
.........
Comparison - greater than or equal
[ True  True]
.................
Comparison - less
[False False]
..................
Comparison - less than or equal
[False  True]


9. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.


In [43]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 50, 85, 93, 150, -147, 120, -60, 70, 100.000001])
print("Original numbers:")
print(x)
print("..............")
print(y)
print("...............")
print("Comparison - equal:")
print(np.equal(x, y))
print("................")
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Original numbers:
[  72   79   85   90  150 -135  120  -10   60  100]
..............
[  72.         50.         85.         93.        150.       -147.
  120.        -60.         70.        100.000001]
...............
Comparison - equal:
[ True False  True False  True False  True False False False]
................
Comparison - equal within a tolerance:
False


10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [31]:
X = np.array([1, 7, 13, 105])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
32 bytes
